# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/svetzal/Work/Personal/C64/r64u

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/svetzal/Work/Personal/C64/r64u

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/svetzal/Work/Personal/C64/r64u/CMakeFiles /Users/svetzal/Work/Personal/C64/r64u//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/svetzal/Work/Personal/C64/r64u/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named r64u

# Build rule for target.
r64u: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r64u
.PHONY : r64u

# fast build rule for target.
r64u/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/build
.PHONY : r64u/fast

#=============================================================================
# Target rules for targets named r64u_autogen_timestamp_deps

# Build rule for target.
r64u_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r64u_autogen_timestamp_deps
.PHONY : r64u_autogen_timestamp_deps

# fast build rule for target.
r64u_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u_autogen_timestamp_deps.dir/build.make CMakeFiles/r64u_autogen_timestamp_deps.dir/build
.PHONY : r64u_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named r64u_autogen

# Build rule for target.
r64u_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r64u_autogen
.PHONY : r64u_autogen

# fast build rule for target.
r64u_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u_autogen.dir/build.make CMakeFiles/r64u_autogen.dir/build
.PHONY : r64u_autogen/fast

r64u_autogen/3YJK5W5UP7/qrc_r64u.o: r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.o
.PHONY : r64u_autogen/3YJK5W5UP7/qrc_r64u.o

# target to build an object file
r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.o
.PHONY : r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.o

r64u_autogen/3YJK5W5UP7/qrc_r64u.i: r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.i
.PHONY : r64u_autogen/3YJK5W5UP7/qrc_r64u.i

# target to preprocess a source file
r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.i
.PHONY : r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.i

r64u_autogen/3YJK5W5UP7/qrc_r64u.s: r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.s
.PHONY : r64u_autogen/3YJK5W5UP7/qrc_r64u.s

# target to generate assembly for a file
r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.s
.PHONY : r64u_autogen/3YJK5W5UP7/qrc_r64u.cpp.s

r64u_autogen/mocs_compilation.o: r64u_autogen/mocs_compilation.cpp.o
.PHONY : r64u_autogen/mocs_compilation.o

# target to build an object file
r64u_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/r64u_autogen/mocs_compilation.cpp.o
.PHONY : r64u_autogen/mocs_compilation.cpp.o

r64u_autogen/mocs_compilation.i: r64u_autogen/mocs_compilation.cpp.i
.PHONY : r64u_autogen/mocs_compilation.i

# target to preprocess a source file
r64u_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/r64u_autogen/mocs_compilation.cpp.i
.PHONY : r64u_autogen/mocs_compilation.cpp.i

r64u_autogen/mocs_compilation.s: r64u_autogen/mocs_compilation.cpp.s
.PHONY : r64u_autogen/mocs_compilation.s

# target to generate assembly for a file
r64u_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/r64u_autogen/mocs_compilation.cpp.s
.PHONY : r64u_autogen/mocs_compilation.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/models/remotefilemodel.o: src/models/remotefilemodel.cpp.o
.PHONY : src/models/remotefilemodel.o

# target to build an object file
src/models/remotefilemodel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/models/remotefilemodel.cpp.o
.PHONY : src/models/remotefilemodel.cpp.o

src/models/remotefilemodel.i: src/models/remotefilemodel.cpp.i
.PHONY : src/models/remotefilemodel.i

# target to preprocess a source file
src/models/remotefilemodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/models/remotefilemodel.cpp.i
.PHONY : src/models/remotefilemodel.cpp.i

src/models/remotefilemodel.s: src/models/remotefilemodel.cpp.s
.PHONY : src/models/remotefilemodel.s

# target to generate assembly for a file
src/models/remotefilemodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/models/remotefilemodel.cpp.s
.PHONY : src/models/remotefilemodel.cpp.s

src/services/c64uftpclient.o: src/services/c64uftpclient.cpp.o
.PHONY : src/services/c64uftpclient.o

# target to build an object file
src/services/c64uftpclient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/c64uftpclient.cpp.o
.PHONY : src/services/c64uftpclient.cpp.o

src/services/c64uftpclient.i: src/services/c64uftpclient.cpp.i
.PHONY : src/services/c64uftpclient.i

# target to preprocess a source file
src/services/c64uftpclient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/c64uftpclient.cpp.i
.PHONY : src/services/c64uftpclient.cpp.i

src/services/c64uftpclient.s: src/services/c64uftpclient.cpp.s
.PHONY : src/services/c64uftpclient.s

# target to generate assembly for a file
src/services/c64uftpclient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/c64uftpclient.cpp.s
.PHONY : src/services/c64uftpclient.cpp.s

src/services/c64urestclient.o: src/services/c64urestclient.cpp.o
.PHONY : src/services/c64urestclient.o

# target to build an object file
src/services/c64urestclient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/c64urestclient.cpp.o
.PHONY : src/services/c64urestclient.cpp.o

src/services/c64urestclient.i: src/services/c64urestclient.cpp.i
.PHONY : src/services/c64urestclient.i

# target to preprocess a source file
src/services/c64urestclient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/c64urestclient.cpp.i
.PHONY : src/services/c64urestclient.cpp.i

src/services/c64urestclient.s: src/services/c64urestclient.cpp.s
.PHONY : src/services/c64urestclient.s

# target to generate assembly for a file
src/services/c64urestclient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/c64urestclient.cpp.s
.PHONY : src/services/c64urestclient.cpp.s

src/services/deviceconnection.o: src/services/deviceconnection.cpp.o
.PHONY : src/services/deviceconnection.o

# target to build an object file
src/services/deviceconnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/deviceconnection.cpp.o
.PHONY : src/services/deviceconnection.cpp.o

src/services/deviceconnection.i: src/services/deviceconnection.cpp.i
.PHONY : src/services/deviceconnection.i

# target to preprocess a source file
src/services/deviceconnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/deviceconnection.cpp.i
.PHONY : src/services/deviceconnection.cpp.i

src/services/deviceconnection.s: src/services/deviceconnection.cpp.s
.PHONY : src/services/deviceconnection.s

# target to generate assembly for a file
src/services/deviceconnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/services/deviceconnection.cpp.s
.PHONY : src/services/deviceconnection.cpp.s

src/ui/preferencesdialog.o: src/ui/preferencesdialog.cpp.o
.PHONY : src/ui/preferencesdialog.o

# target to build an object file
src/ui/preferencesdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/ui/preferencesdialog.cpp.o
.PHONY : src/ui/preferencesdialog.cpp.o

src/ui/preferencesdialog.i: src/ui/preferencesdialog.cpp.i
.PHONY : src/ui/preferencesdialog.i

# target to preprocess a source file
src/ui/preferencesdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/ui/preferencesdialog.cpp.i
.PHONY : src/ui/preferencesdialog.cpp.i

src/ui/preferencesdialog.s: src/ui/preferencesdialog.cpp.s
.PHONY : src/ui/preferencesdialog.s

# target to generate assembly for a file
src/ui/preferencesdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r64u.dir/build.make CMakeFiles/r64u.dir/src/ui/preferencesdialog.cpp.s
.PHONY : src/ui/preferencesdialog.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... r64u_autogen"
	@echo "... r64u_autogen_timestamp_deps"
	@echo "... r64u"
	@echo "... r64u_autogen/3YJK5W5UP7/qrc_r64u.o"
	@echo "... r64u_autogen/3YJK5W5UP7/qrc_r64u.i"
	@echo "... r64u_autogen/3YJK5W5UP7/qrc_r64u.s"
	@echo "... r64u_autogen/mocs_compilation.o"
	@echo "... r64u_autogen/mocs_compilation.i"
	@echo "... r64u_autogen/mocs_compilation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/models/remotefilemodel.o"
	@echo "... src/models/remotefilemodel.i"
	@echo "... src/models/remotefilemodel.s"
	@echo "... src/services/c64uftpclient.o"
	@echo "... src/services/c64uftpclient.i"
	@echo "... src/services/c64uftpclient.s"
	@echo "... src/services/c64urestclient.o"
	@echo "... src/services/c64urestclient.i"
	@echo "... src/services/c64urestclient.s"
	@echo "... src/services/deviceconnection.o"
	@echo "... src/services/deviceconnection.i"
	@echo "... src/services/deviceconnection.s"
	@echo "... src/ui/preferencesdialog.o"
	@echo "... src/ui/preferencesdialog.i"
	@echo "... src/ui/preferencesdialog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

