// Link-time stubs for ExploreNavigationController unit tests.
//
// ExploreNavigationController calls methods on RemoteFileModel,
// DeviceConnection, and ExploreFavoritesController only when those pointers
// are non-null. Tests pass nullptr for all three, so these bodies are never
// reached — but the linker still demands their symbols, including those
// generated by MOC for Q_OBJECT classes.

#include "models/remotefilemodel.h"
#include "services/deviceconnection.h"
#include "ui/explorefavoritescontroller.h"

// ---------------------------------------------------------------------------
// RemoteFileModel stubs
// ---------------------------------------------------------------------------

RemoteFileModel::RemoteFileModel(QObject *parent) : QAbstractItemModel(parent), rootNode_(nullptr)
{
}

RemoteFileModel::~RemoteFileModel() = default;

void RemoteFileModel::setFtpClient(IFtpClient * /*client*/) {}
void RemoteFileModel::setRootPath(const QString & /*path*/) {}
void RemoteFileModel::refresh() {}
void RemoteFileModel::refresh(const QModelIndex & /*index*/) {}
void RemoteFileModel::clear() {}
void RemoteFileModel::invalidateCache() {}
void RemoteFileModel::invalidatePath(const QString & /*path*/) {}
void RemoteFileModel::refreshIfStale() {}
bool RemoteFileModel::isDirectory(const QModelIndex & /*index*/) const { return false; }
bool RemoteFileModel::isStale(const QModelIndex & /*index*/) const { return false; }

QString RemoteFileModel::filePath(const QModelIndex & /*index*/) const { return {}; }
filetype::FileType RemoteFileModel::fileType(const QModelIndex & /*index*/) const
{
    return filetype::FileType::Unknown;
}
qint64 RemoteFileModel::fileSize(const QModelIndex & /*index*/) const { return 0; }

filetype::FileType RemoteFileModel::detectFileType(const QString & /*filename*/)
{
    return filetype::FileType::Unknown;
}
QIcon RemoteFileModel::iconForFileType(filetype::FileType /*type*/) { return {}; }
QString RemoteFileModel::fileTypeString(filetype::FileType /*type*/) { return {}; }

QModelIndex RemoteFileModel::index(int /*row*/, int /*column*/,
                                    const QModelIndex & /*parent*/) const
{
    return {};
}
QModelIndex RemoteFileModel::parent(const QModelIndex & /*child*/) const { return {}; }
int RemoteFileModel::rowCount(const QModelIndex & /*parent*/) const { return 0; }
int RemoteFileModel::columnCount(const QModelIndex & /*parent*/) const { return 0; }
QVariant RemoteFileModel::data(const QModelIndex & /*index*/, int /*role*/) const { return {}; }
QVariant RemoteFileModel::headerData(int /*section*/, Qt::Orientation /*orientation*/,
                                      int /*role*/) const
{
    return {};
}
bool RemoteFileModel::hasChildren(const QModelIndex & /*parent*/) const { return false; }
bool RemoteFileModel::canFetchMore(const QModelIndex & /*parent*/) const { return false; }
void RemoteFileModel::fetchMore(const QModelIndex & /*parent*/) {}
Qt::ItemFlags RemoteFileModel::flags(const QModelIndex & /*index*/) const
{
    return Qt::NoItemFlags;
}

// MOC-required private slots
void RemoteFileModel::onDirectoryListed(const QString & /*path*/,
                                         const QList<FtpEntry> & /*entries*/)
{
}
void RemoteFileModel::onFtpError(const QString & /*message*/) {}

// ---------------------------------------------------------------------------
// DeviceConnection stubs
// ---------------------------------------------------------------------------

DeviceConnection::DeviceConnection(QObject *parent) : QObject(parent) {}
DeviceConnection::DeviceConnection(IRestClient * /*restClient*/, IFtpClient * /*ftpClient*/,
                                    QObject *parent)
    : QObject(parent)
{
}
DeviceConnection::~DeviceConnection() = default;

void DeviceConnection::setHost(const QString & /*host*/) {}
void DeviceConnection::setPassword(const QString & /*password*/) {}
void DeviceConnection::setAutoReconnect(bool /*enabled*/) {}
void DeviceConnection::connectToDevice() {}
void DeviceConnection::disconnectFromDevice() {}
void DeviceConnection::refreshDeviceInfo() {}
void DeviceConnection::refreshDriveInfo() {}

// MOC-required private slots
void DeviceConnection::onRestInfoReceived(const DeviceInfo & /*info*/) {}
void DeviceConnection::onRestDrivesReceived(const QList<DriveInfo> & /*drives*/) {}
void DeviceConnection::onRestConnectionError(const QString & /*error*/) {}
void DeviceConnection::onRestOperationFailed(const QString & /*operation*/,
                                              const QString & /*error*/)
{
}
void DeviceConnection::onFtpConnected() {}
void DeviceConnection::onFtpDisconnected() {}
void DeviceConnection::onFtpError(const QString & /*message*/) {}
void DeviceConnection::onReconnectTimer() {}

// ---------------------------------------------------------------------------
// ExploreFavoritesController stubs
// ---------------------------------------------------------------------------

ExploreFavoritesController::ExploreFavoritesController(FavoritesManager * /*favoritesManager*/,
                                                        QObject *parent)
    : QObject(parent)
{
}

void ExploreFavoritesController::setToggleAction(QAction * /*action*/) {}
void ExploreFavoritesController::setFavoritesMenu(QMenu * /*menu*/) {}
void ExploreFavoritesController::updateForPath(const QString & /*path*/) {}
bool ExploreFavoritesController::isFavorite(const QString & /*path*/) const { return false; }
void ExploreFavoritesController::onToggleFavorite(const QString & /*path*/) {}
void ExploreFavoritesController::onFavoriteSelected(QAction * /*action*/) {}
void ExploreFavoritesController::onFavoritesChanged() {}
